name = "cf-bot" # todo
main = "js/_worker.js"
workers_dev = true
compatibility_date = "2024-03-20"

[[routes]]
pattern = "dns-cloudproxyip.c-bnn.xyz"
custom_domain = true

[[routes]]
pattern = "live.iflix.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "zoomcares.zoom.us.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "partner.zoom.us.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "zoomgov.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "gomarketplacecontent-cf.zoom.us.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "investors.fb.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "bimbel.ruangguru.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "edu.ruangguru.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.sea-sw.swiftserve.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "api.blibli.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "unnes.ac.id.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "fikom.esaunggul.ac.id.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "app.gopay.co.id.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "chat.sociomile.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "api.quipper.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "ganecadigital.com.sg-chers.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "stripchat.page.sg-chers.c-bnn.xyz"
custom_domain = true
