name = "cf" # todo
main = "js/_worker.js"
workers_dev = true
compatibility_date = "2024-03-20"

[[routes]]
pattern = "killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.killswitch.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.killswitch.turah.my.id"
custom_domain = true
[[routes]]
pattern = "killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.killswitch.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.killswitch.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.killswitch.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.killswitch.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.killswitch.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.killswitch.najah.biz.id"
custom_domain = true

[[routes]]
pattern = "killswitch.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.killswitch.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.killswitch.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.killswitch.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.killswitch.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.killswitch.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.killswitch.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.killswitch.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.killswitch.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.killswitch.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.killswitch.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.killswitch.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.killswitch.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.killswitch.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.killswitch.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.killswitch.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.killswitch.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
