name = "cf" # todo
main = "js/_worker.js"
workers_dev = true
compatibility_date = "2024-03-20"

[[routes]]
pattern = "anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.anonimitas.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.anonimitas.turah.my.id"
custom_domain = true
[[routes]]
pattern = "anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.anonimitas.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.anonimitas.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.anonimitas.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.anonimitas.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.anonimitas.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.anonimitas.najah.biz.id"
custom_domain = true

[[routes]]
pattern = "anonimitas.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.anonimitas.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.anonimitas.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.anonimitas.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.anonimitas.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.anonimitas.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.anonimitas.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.anonimitas.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.anonimitas.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.anonimitas.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.anonimitas.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.anonimitas.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.anonimitas.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.anonimitas.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.anonimitas.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.anonimitas.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.anonimitas.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
