name = "cf" # todo
main = "js/_worker.js"
workers_dev = true
compatibility_date = "2024-03-20"

[[routes]]
pattern = "multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.multihop.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.multihop.turah.my.id"
custom_domain = true
[[routes]]
pattern = "multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.multihop.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.multihop.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.multihop.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.multihop.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.multihop.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.multihop.najah.biz.id"
custom_domain = true

[[routes]]
pattern = "multihop.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.multihop.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.multihop.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.multihop.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.multihop.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.multihop.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.multihop.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.multihop.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.multihop.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.multihop.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.multihop.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.multihop.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.multihop.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.multihop.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.multihop.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.multihop.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.multihop.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
