name = "cf" # todo
main = "js/_worker.js"
workers_dev = true
compatibility_date = "2024-03-20"

[[routes]]
pattern = "kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.kriptografi.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.kriptografi.turah.my.id"
custom_domain = true
[[routes]]
pattern = "kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.kriptografi.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.kriptografi.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.kriptografi.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.kriptografi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.kriptografi.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.kriptografi.najah.biz.id"
custom_domain = true

[[routes]]
pattern = "kriptografi.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.kriptografi.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.kriptografi.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.kriptografi.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.kriptografi.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.kriptografi.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.kriptografi.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.kriptografi.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.kriptografi.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.kriptografi.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.kriptografi.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.kriptografi.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.kriptografi.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.kriptografi.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.kriptografi.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.kriptografi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.kriptografi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
